export const menu = [
  {
    id: 1,
    title: 'item-1',
    category: 'category-1',
    price: 15.99,
    qty: 0,
    img: "./ctg_images/item-1.jpg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'item-2',
    category: 'category-4',
    price: 13.99,
    qty: 0,
    img: './ctg_images/item-2.jpg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. `,
  },
  {
    id: 3,
    title: 'item-3',
    category: 'category-3',
    price: 6.99,
    qty: 0,
    img: './ctg_images/item-3.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'item-4',
    category: 'category-2',
    price: 20.99,
    qty: 0,
    img: './ctg_images/item-4.jpg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'item-5',
    category: 'category-3',
    price: 22.99,
    qty: 0,
    img: './ctg_images/item-5.jpg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'item-6',
    category: 'category-2',
    price: 18.99,
    qty: 0,
    img: './ctg_images/item-6.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'item-7',
    category: 'category-1',
    price: 8.99,
    qty: 0,
    img: './ctg_images/item-7.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'item-8',
    category: 'category-4',
    price: 12.99,
    qty: 0,
    img: './ctg_images/item-8.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'item-9',
    category: 'category-1',
    price: 16.99,
    qty: 0,
    img: './ctg_images/item-9.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'item-10',
    category: 'category-4',
    price: 15.99,
    qty: 0,
    img: './ctg_images/item-10.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 11,
    title: 'item-11',
    category: 'category-2',
    price: 15.99,
    qty: 0,
    img: './ctg_images/item-11.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 12,
    title: 'item-12',
    category: 'category-2',
    price: 15.99,
    qty: 0,
    img: './ctg_images/item-12.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 13,
    title: 'item-13',
    category: 'category-4',
    price: 15.99,
    qty: 0,
    img: './ctg_images/item-13.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 14,
    title: 'item-14',
    category: 'category-3',
    price: 15.99,
    qty: 0,
    img: './ctg_images/item-14.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 15,
    title: 'item-15',
    category: 'category-1',
    price: 15.99,
    qty: 0,
    img: './ctg_images/item-15.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 16,
    title: 'item-16',
    category: 'category-3',
    price: 15.99,
    qty: 0,
    img: './ctg_images/item-16.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
];


export const detailProduct = {
  id: 1,
  title: "Google Pixel - Black",
  img: "./ctg_images/item-15.jpg",
  price: 10,
  company: "google",
  info:
    "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0
};
